version: '2'

services:

  jenkins:
    container_name: jenkins
    image: jenkinsuoc:latest
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      bridge:
        ipv4_address: 172.16.0.5

  registry:
    container_name: registry
    image: registry
    restart: always
    ports:
      - "5050:5000"
    volumes:
      - $PWD/registry:/var/lib/registry
    networks:
      bridge:
        ipv4_address: 172.16.0.6

networks:
  bridge:
    driver: "bridge"
    ipam:
     config:
       - subnet: 172.16.0.0/16
         gateway: 172.16.0.1


